# Generated by Django 5.1.3 on 2025-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoraGuchiApp', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
    ]
