# Generated by Django 5.1.3 on 2025-03-21 09:01

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoraGuchiApp', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_activate_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activate_token',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
