# Generated by Django 5.1.3 on 2025-03-22 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoraGuchiApp', '0005_useractivatetoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useractivatetoken',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
